# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yetda' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yetda

  pod 'KakaoSDK'
  pod 'Firebase/Auth', '8.6.0'
  pod 'Firebase/Firestore', '8.6.0'
  pod 'GoogleSignIn', '5.0.2'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
  end
end