//
//  SearchSiteModel.swift
//  Yetda
//
//  Created by rbwo on 2022/07/25.
//

import Foundation

struct SearchModel: Hashable {
    static let dataModel: [String] = ["Aichi" , "아이치",
                                        "Akita" , "아키타",
                                        "Aomori" , "아오모리",
                                        "Chiba" , "치바",
                                        "Ehime" , "에히메",
                                        "Fukui" , "후쿠이",
                                        "Fukuoka" , "후쿠오카",
                                        "Fukushima" , "후쿠시마",
                                        "Gihu" , "기후",
                                        "Gunma" , "군마",
                                        "Hiroshima" , "히로시마",
                                        "Hokkaido" , "홋카이도",
                                        "Hyogo" , "효고",
                                        "Ibaraki" , "이바라키",
                                        "Ishikawa" , "이시카와",
                                        "Iwate" , "이와테",
                                        "Kagawa" , "가가와",
                                        "Kagoshima" , "가고시마",
                                        "Kanagawa" , "가나가와",
                                        "Kochi" , "고치",
                                        "Kumamoto" , "구마모토",
                                        "Kyoto" , "교토",
                                        "Mie" , "미에",
                                        "Miyagi" , "미야기",
                                        "Miyazaki" , "미야자키",
                                        "Nagano" , "나가노",
                                        "Nagasaki" , "나가사키",
                                        "Nara" , "나라",
                                        "Niigata" , "니이가타",
                                        "Oita" , "오이타",
                                        "Okayama" , "오카야마",
                                        "Okinawa" , "오키나와",
                                        "Osaka" , "오사카",
                                        "Saga" , "사가",
                                        "Saitama" , "사이타마",
                                        "Shiga" , "시가",
                                        "Shimane" , "시마네",
                                        "Shizuoka" , "시즈오카",
                                        "Tochigi" , "도치기",
                                        "Tokushima" , "도쿠시마",
                                        "Tokyo" , "도쿄",
                                        "Tottori" , "돗토리",
                                        "Toyama" , "도야마",
                                        "Wakayama" , "와카야마",
                                        "Yamagata" , "야마가타",
                                        "Yamaguchi" , "야마구치",
                                      "Yamanashi" , "야마나시",
                                      "aichi" ,
                                      "akita" ,
                                      "aomori" ,
                                      "chiba" ,
                                      "ehime" ,
                                      "fukui" ,
                                      "fukuoka" ,
                                      "fukushima" ,
                                      "gihu" ,
                                      "gunma" ,
                                      "hiroshima",
                                      "hokkaido" ,
                                      "hyogo" ,
                                      "ibaraki" ,
                                      "ishikawa" ,
                                      "iwate" ,
                                      "kagawa" ,
                                      "kagoshima" ,
                                      "kanagawa" ,
                                      "kochi" ,
                                      "kumamoto" ,
                                      "kyoto" ,
                                      "mie" ,
                                      "miyagi" ,
                                      "miyazaki" ,
                                      "nagano" ,
                                      "nagasaki" ,
                                      "nara" ,
                                      "niigata" ,
                                      "oita" ,
                                      "okayama",
                                      "okinawa" ,
                                      "osaka" ,
                                      "saga" ,
                                      "saitama" ,
                                      "shiga" ,
                                      "shimane" ,
                                      "shizuoka" ,
                                      "tochigi" ,
                                      "tokushima" ,
                                      "tokyo" ,
                                      "tottori" ,
                                      "toyama" ,
                                      "wakayama" ,
                                      "yamagata" ,
                                      "yamaguchi" ,
                                      "yamanashi" ,
                                                    ]
}
